name: Deploy vers Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Retirer les fichiers Faiss
        run: |
          git config user.email "ci@github.com"
          git config user.name "CI"
          git rm -r --cached utils/faiss_index || true
          git rm --cached *.faiss || true
          git commit -m "Retire les Faiss pour HF" || true

      - name: Pousser vers HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://lealjo27:$HF_TOKEN@huggingface.co/spaces/lealjo27/Projet7_Evenementiel main --force
